"""initial migtation

Revision ID: 0829d86a08da
Revises: 
Create Date: 2017-04-12 17:05:01.974423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0829d86a08da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jokes')
    op.drop_table('movies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.CHAR(length=255), nullable=True),
    sa.Column('imgUrl', mysql.CHAR(length=255), nullable=True),
    sa.Column('point', mysql.FLOAT(precision=2, scale=1), nullable=True),
    sa.Column('director', mysql.CHAR(length=255), nullable=True),
    sa.Column('intro', mysql.TEXT(), nullable=True),
    sa.Column('type', mysql.CHAR(length=50), nullable=True),
    sa.Column('time', mysql.CHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('jokes',
    sa.Column('cont', mysql.TEXT(), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
